/** Public prices are fresh for 90 seconds and retained for six hours. */
export const PUBLIC_PRICES_TTL_SECONDS = 90;
export const PUBLIC_PRICES_REFRESH_INTERVAL_MS = PUBLIC_PRICES_TTL_SECONDS * 1_000;
export const PUBLIC_PRICES_EDGE_STALE_SECONDS = PUBLIC_PRICES_TTL_SECONDS * 3;
export const PUBLIC_PRICES_RETAINED_SECONDS = 6 * 60 * 60;
export const PUBLIC_PRICES_FAILURE_RETRY_SECONDS = 30;
export const PUBLIC_PRICES_REFRESH_TIMEOUT_MS = 90_000;
